--------------------------------------------------------
--  File created - Thursday-September-08-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BANK
--------------------------------------------------------

  CREATE TABLE "SCOTT"."BANK" 
   (	"ACCOUNT_NAME" VARCHAR2(255 BYTE), 
	"ACCOUNTNUMBER" VARCHAR2(255 BYTE), 
	"TOTALBALANCE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.BANK
SET DEFINE OFF;
Insert into SCOTT.BANK (ACCOUNT_NAME,ACCOUNTNUMBER,TOTALBALANCE) values (' sonii','678','9000');
Insert into SCOTT.BANK (ACCOUNT_NAME,ACCOUNTNUMBER,TOTALBALANCE) values (' Manish','98','1000');
Insert into SCOTT.BANK (ACCOUNT_NAME,ACCOUNTNUMBER,TOTALBALANCE) values (' Mahendra kumar ','9090','6000');
Insert into SCOTT.BANK (ACCOUNT_NAME,ACCOUNTNUMBER,TOTALBALANCE) values ('Rajesh','35453553535','-292100.0');
Insert into SCOTT.BANK (ACCOUNT_NAME,ACCOUNTNUMBER,TOTALBALANCE) values (' sourav','567','4099');
Insert into SCOTT.BANK (ACCOUNT_NAME,ACCOUNTNUMBER,TOTALBALANCE) values (' Sonuu','23','4000');
Insert into SCOTT.BANK (ACCOUNT_NAME,ACCOUNTNUMBER,TOTALBALANCE) values ('Amaan','2345','6100');
Insert into SCOTT.BANK (ACCOUNT_NAME,ACCOUNTNUMBER,TOTALBALANCE) values (' Sonu','123456','7000');
Insert into SCOTT.BANK (ACCOUNT_NAME,ACCOUNTNUMBER,TOTALBALANCE) values ('Amaan','2345','6100');
